# Generated by Django 5.1.4 on 2025-01-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_alter_doctor_mobile_alter_patient_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
